apiVersion: v2
name: langfuse
description: LLM engineering platform - LLM observability, metrics, evaluations, prompt management.
icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/langfuse.png
keywords:
  - langfuse
  - llm
  - observability
  - prompt management
  - metrics
home: https://langfuse.com/
sources:
  - https://github.com/langfuse/langfuse
  - https://github.com/langfuse/langfuse-k8s
type: application
version: 1.0.13
appVersion: "3.63.1"
dependencies:
- name: langfuse
  version: 1.2.13
  repository: https://langfuse.github.io/langfuse-k8s
- name: library-chart
  version: 1.7.14
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
